### ISSUE TITLE
How to prevent word break to occur anywhere in a word and to align the keys at the top?

### ISSUE THREAD

**Issue by KelSolaar** [andypf/json-viewer#18]
Hello,

I tried to use custom CSS to override some styling elements but it did not work, e.g.,

```css
        .data-row .value.string {
            word-break: break-word !important;
            color: #FF0000 !important;
        }
```
Specifically, I would like to avoid word break to happen anywhere in a word, for long text, it makes the output unreadable:

![image](https://github.com/user-attachments/assets/8870fe84-6737-4163-a761-abdc395ae1c3)

Also, the key, e.g., `token` here, would probably be better at the top, especially when there a lot of items with long text, having it in the middle makes it harder to partition elements visually.

Cheers,

Thomas
